### ISSUE TITLE
[Bug] NosoWallet timing out when first connecting

### ISSUE THREAD

**Issue by leviable** [Noso-Project/NosoWallet#11]
When the NosoWallet first connects to nodes to sync the blockchain, it can timeout if the process takes longer than 15 seconds.

Steps to reproduce:
1) Create a fresh directory and add the 0.2.1F version of the Noso binary
2) Run the binary without autoconnecting
3) Connect to a node via the console: `connectto 75.127.0.216`

Expected result:
1) Wallet connects to node
2) Wallet downloads all blocks
3) Wallet rebuilds block summary
4) Wallet is synced and online

Actual Result:
1) Wallet connects to node
2) Wallet downloads all blocks
3) Wallet rebuilds block summary
4) Wallet disconnects with the follow message: 
```
Sumary completed from 1 to 15469
Conection closed: Time Out Auth -> 75.127.0.216
Disconnected.
```

It appears that this happens specifically during the `rebuilding sumary block` phase. I would guess that, during that activity, the wallet is unable to send a PING, and eventually closes the connection after 15 seconds has passed.
https://github.com/Noso-Project/NosoWallet/blob/main/mpred.pas#L447-L453

**Comment by leviable** [comment]
Also, during the `rebuilding sumary block` phase, the clock in the lower left continues to update, however the spinner in the lower left is frozen for the duration of the `rebuilding sumary block` phase. Perhaps some sort of tight loop is preventing a connecting keep-alive (PING?) from getting sent?

**Comment by eswar159** [comment]
Hi @leviable sir
can u please elaborate the process like more detailed with screenshots so it will easy for beginners like me

![2021-09-13](https://user-images.githubusercontent.com/35969578/133068206-67538cdd-444a-4490-8379-d426305ac18f.png)


Thank you

**Comment by DevTeamNoso** [comment]
> Hi @leviable sir can u please elaborate the process like more detailed with screenshots so it will easy for beginners like me
> 
> ![2021-09-13](https://user-images.githubusercontent.com/35969578/133068206-67538cdd-444a-4490-8379-d426305ac18f.png)
> 
> Thank you

Sorry, i believe you are talking about the noso-go miner; issues about it should be reported on its own repo.

> Also, during the `rebuilding sumary block` phase, the clock in the lower left continues to update, however the spinner in the lower left is frozen for the duration of the `rebuilding sumary block` phase. Perhaps some sort of tight loop is preventing a connecting keep-alive (PING?) from getting sent?

Clock is controlled by a different thread (the one that controls the anti-hang system), thats the reason it still continue updating, meanwhile the little fan is updated by the app main thread, which is busy rebuilding the summary.
Keep the wallet connected meanwhile the summary is rebuilded is not really necessary; is it not verified yet if the blockchain the wallet have is the correct (consensus) one, so the wallet need verify it before; thats the reason the process of rebuild the summary is a blocking one for the main thread.

It should not be difficult to keep the connections while the process is run, but i can not figure a good reason or a need for that.
