### ISSUE TITLE
BANNED

### ISSUE THREAD

**Issue by karlkiesinger** [Noso-Project/NosoWallet#13]
My IP address is BANNED. it was because I ran to wallet 2  program on the same PC at the same time.
How Long dose the BANNED stay active?

Thank you
Karl K

**Comment by karlkiesinger** [comment]
after some time I was able to get back on the network
I would like to know how long it would take?

**Comment by gcarreno** [comment]
Hey @karlkiesinger,

From what I'm aware, all the bans are cleared at 00:00 UTC.

You just have to calculate that into your time zone and you'll know at what time of your day it will be reset.

I'm closing this issue since it seams that it's all resolved.

Cheers,
Gus
