### ISSUE TITLE
Write lines from Console tab to file

### ISSUE THREAD

**Issue by leviable** [Noso-Project/NosoWallet#14]
As someone trying to run a headless node from within a docker container, I need to see the contents of the Console tab, but without looking at the GUI.

Preferably, anything written to the Console tab should also be written to stdout. If that isn't possible, write Console tab lines to a new log file, such as `console.txt` or similar.

**Comment by DevTeamNoso** [comment]
An mentioned in otehr issue, now console output is also directed to a log file. Thanks.
