### ISSUE TITLE
pool not starting up

### ISSUE THREAD

**Issue by karlkiesinger** [Noso-Project/NosoWallet#16]
Hi All,
I had a pool working for some time and now it is not starting up.
When I try to connecting  I get No connection could be made because the target machine actively refused it.

I do take the source code and make the program. 

I am running 0.3.Aa68 here is what I see on startup.

`PoolMaxMembers:1000
NosoWallet 0.3.0Aa68
>> connect
Trying connection to servers
Connected.
Headers file requested
Receiving headers
Headers file received: 30AC3
LastBlock requested from block 46997
Blocks received up to 47097
LastBlock requested from block 47097
Blocks received up to 47197
LastBlock requested from block 47197
Blocks received up to 47297
LastBlock requested from block 47297
Blocks received up to 47397
LastBlock requested from block 47397
Blocks received up to 47497
LastBlock requested from block 47497
Blocks received up to 47564
Sumary completed from 46998 to 47564
Updated!
Connection Closed Gracefully.
Pending requested to 
Master nodes requested
Connection Closed Gracefully.
>> serveron
Server ENABLED. Listening on port 8080
My Masternode reported
My Masternode reported
Connection Closed Gracefully.
Master nodes requested
My Masternode reported
My Masternode reported
My Masternode reported
Connection Closed Gracefully.
My Masternode reported
My Masternode reported
My Masternode reported
Headers file requested
Receiving headers
Headers file received: E7CF5
LastBlock requested from block 47564
My Masternode reported
Blocks received up to 47565
Sumary completed from 47565 to 47565
`

**Comment by DevTeamNoso** [comment]
Pool was removed from nosowallet. Use consopool instead. Thanks.
