### ISSUE TITLE
[Feature] Support connecting to and querying a pool without joining it

### ISSUE THREAD

**Issue by leviable** [Noso-Project/NosoWallet#2]
In order to support development of 3rd party tools to monitor on and report pool information, it would be useful if we could connect to a pool and query it for information without joining it.

Things worth querying:
* Pool hash rate
* Number of miners in pool
* Total pool size

**Comment by DevTeamNoso** [comment]
Implemented:
Request -> {PoolPassword} {ValidNosoaddress} STATUS
Response -> STATUS {hashrate} {fee} {share} {minerCount} [list of miners: {address}:{balance}:{blocks_until_paymet}]

**Comment by leviable** [comment]
Awesome, thanks DTN
