### ISSUE TITLE
Value of "BANNED" on the Auto IP

### ISSUE THREAD

**Issue by gcarreno** [Noso-Project/NosoWallet#31]
Hey Y'all,

This just happened to me:

![image](https://github.com/user-attachments/assets/090c2a74-cafa-48bb-977c-6f7271424450)

After some talks with _bermello_ I'm posting this as an issue in order for us to use this functionality provided by GitHub.

Cheers,
Gus

**Comment by NosoDevTeam** [comment]
This was caused due to lack of variable verification on incoming IPs requests. Already fixed on code and will be available on next commit. Thanks for reporting.

**Comment by gcarreno** [comment]
Hey @NosoDevTeam,

Is it OK to then close this issue?

Cheers,
Gus
