### ISSUE TITLE
Add handlers for unix signals

### ISSUE THREAD

**Issue by leviable** [Noso-Project/NosoWallet#5]
I am attempting to containerize the Noso wallet for eventual deployment in a kubernetes cluster. In order to fully support that, the noso wallet must handle unix signals, such as SIGINT, SIGTERM, etc.

I attempted to add the functionality myself, but after speaking with @gcarreno I believe the current wallet implementation makes this task too difficult for me.

**Comment by leviable** [comment]
Some references for how other FPC programs do this:

http://tech406.com/kdocs/signals.xml
https://fossies.org/linux/fpcbuild/fpcsrc/packages/fcl-extra/src/unix/daemonapp.inc

**Comment by DevTeamNoso** [comment]
Now console output is sent directly to a log file.
