### ISSUE TITLE
Write log lines from Noso console to StdOut and/or log file

### ISSUE THREAD

**Issue by leviable** [Noso-Project/NosoWallet#8]
```
As a Noso node operator
I would like to have the log lines found in the Noso console also logged to StdOut and/or a log file
So that I can monitor the logs without needing to view the Noso GUI
```

I plan to run a Noso node (and eventually a master node) in a headless kubernetes cluster where I will not have access to the GUI. It would be very helpful if the log lines found in the Noso wallet console could also be directed to StdOut, and logged to a file.

**Comment by DevTeamNoso** [comment]
Currently there is a file called /nosodata/errorlog.txt that stores all the log lines.
